-- ============================================================
-- ASSIGNMENT 7: PART C — JOINS
-- NAME: AKHILA ANISH DAS
-- ROLL NO: 150096725016
-- ============================================================


-- Q1. Using INNER JOIN across all three tables,
-- list every order with customer_name, product_name,
-- quantity and order_date.

-- Name: AKHILA ANISH DAS, Roll No: 150096725016

SELECT o.order_id,
    c.customer_name,
    p.product_name,
    o.quantity,
    o.order_date
FROM orders o
INNER JOIN customers c
ON o.customer_id = c.customer_id
INNER JOIN products p
ON o.product_id = p.product_id;


-- Q2. Using LEFT JOIN from customers to orders,
-- list every customer and their orders.
-- Customers with no orders should still appear.

-- Name: AKHILA ANISH DAS, Roll No: 150096725016

SELECT c.customer_id,
    c.customer_name,
    o.order_id,
    o.product_id,
    o.order_date,
    o.quantity
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id;


-- Q3. Using LEFT JOIN from products to orders,
-- list every product and its orders.
-- Products that have never been ordered should still appear.

-- Name: AKHILA ANISH DAS, Roll No: 150096725016

SELECT p.product_id,
    p.product_name,
    o.order_id,
    o.customer_id,
    o.quantity,
    o.order_date
FROM products p
LEFT JOIN orders o
ON p.product_id = o.product_id;


-- Q4. Write a CROSS JOIN between customers and products.
-- The result contains 100 rows because there are 10 customers
-- and 10 products. A CROSS JOIN creates every possible
-- customer-product combination, so it is rarely useful on its
-- own because it can produce a very large number of rows.

-- Name: AKHILA ANISH DAS, Roll No: 150096725016

SELECT c.customer_name,
    p.product_name
FROM customers c
CROSS JOIN products p;


-- Q5. Using JOIN and GROUP BY, calculate total revenue
-- generated by each customer, sorted from highest to lowest.

-- Name: AKHILA ANISH DAS, Roll No: 150096725016

SELECT c.customer_id,
    c.customer_name,
       SUM(p.price * o.quantity) AS total_revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN products p
ON o.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_revenue DESC;


-- Q6. Using LEFT JOIN and WHERE/IS NULL,
-- list all customers who have never placed an order.

-- Name: AKHILA ANISH DAS, Roll No: 150096725016

SELECT c.customer_id,
    c.customer_name
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;